### ISSUE TITLE
Preventing circular dependency

### ISSUE THREAD

**Issue by divick** [openwisp/django-swappable-models#14]
I have the following models for my reusableapp:

```
class BaseParent(models.Model):
    name = models.CharField(max_length=32)
    authors = models.ManyToManyField('reusableapp.Author')

    class Meta:
        abstract = True

class Parent(BaseParent):
    class Meta:
        swappable = swapper.swappable_setting('reusableapp', 'Parent')

class Author(models.Model):
    name = models.CharField(max_length=32)
```

Here are the migrations for the reusableapp:

```
from __future__ import unicode_literals
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
```

```
from __future__ import unicode_literals
from django.db import migrations, models
import swapper

class Migration(migrations.Migration):

    dependencies = [
        ('reusableapp', '0001_initial'),
        swapper.dependency('reusableapp', 'Parent')
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'swappable': swapper.swappable_setting('reusableapp', 'Parent')
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='authors',
            field=models.ManyToManyField(to='reusableapp.Author'),
        ),
    ]
```

Now in myapp I have:

```
from django.db import models
from reusableapp.models import BaseParent

class Parent(BaseParent):
    extra_field = models.CharField(max_length=32)

```

And in myapp settings I have:

`REUSABLEAPP_PARENT_MODEL = 'myapp.Parent'`

On running makemigrations it generates the following migration for myapp:

```
from __future__ import unicode_literals
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('reusableapp', '0002_auto_20170414_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('extra_field', models.CharField(max_length=32)),
                ('authors', models.ManyToManyField(to='reusableapp.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
```

But it leads to circular dependency as can be seen when running migrate on myapp:

> django.db.migrations.exceptions.CircularDependencyError: myapp.0001_initial, reusableapp.0002_auto_20170414_1447

As per the documentation I have added the dependency on Parent in my 0002_auto... migration:

`swapper.dependency('reusableapp', 'Parent')`

If I remove this dependency, then my migrations run fine. Either I am missing something or the documentation requires some changes?

**Comment by blag** [comment]
I think you have misunderstood how to modify your migration files.

You need to remove the circular dependency from `reusableapp/migrations/0002_auto_20170414_1447.py`:

```diff
     dependencies = [
         ('reusableapp', '0001_initial'),
-        swapper.dependency('reusableapp', 'Parent')
     ]
```

Make sure you **KEEP** the `swapper.swappable_setting` line though:

```python
            options={
                'swappable': swapper.swappable_setting('reusableapp', 'Parent')
            },
```

**Comment by divick** [comment]
@blag Thanks for replying on this. Yeah as I mentioned, removing this line from my reusable app makes it work but as per the documentation, see README.md line number 124-125 it has:

 ```
<          migrations.swappable_dependency(settings.REUSABLEAPP_PARENT_MODEL),  
>          swapper.dependency('reusableapp', 'Parent') 
```
So it seems to suggest to add the line "swapper.dependency('reusableapp', 'Parent')". What am I missing here?

**Comment by blag** [comment]
Let's say your swappable model is `Thing` and it inherits from `AbstractBaseThing`:

`reuseable/models.py`:

```python
class AbstractBaseThing(models.Model):
    ...

    class Meta:
        abstract = True

class Thing(AbstractBaseThing):
    class Meta:
        swappable = swapper.swappable_setting('reuseable', 'Thing')
```

you need to tell Django to create the model, *unless* it's been swapped out:

`reuseableapp/migrations/0001_initial.py`:

```python
import swapper

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AbstractBaseThing',
            fields=[
                ...
            ],
            options={
                'abstract': True,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ...
            ],
            options={
                # IIRC, originally should be
                # 'swappable': 'REUSEABLE_THING_MODEL',
                'swappable': swapper.swappable_setting('reuseable', 'Thing'),
            },
        ),
    ]
```

All of that does is **set up** the swappable model. The migrations within `reuseable` are standalone, there are no circular dependencies. If you don't set the `REUSEABLE_THING_MODEL` setting in your `<project>/settings.py` Django will create the concrete `Thing` model as normal.

When you want to swap it out for another model, you'll need to create a further model and migration in their own (separate) app:

`myapp/models.py`:

```python
class NewThing(AbstractBaseThing):
    ...
```

Django is smart enough to generate swappable migrations, but isn't smart enough to generate them with swapper, so you'll need to make sure it uses the correct migrations:

`myapp/migrations/0001_initial.py`:

```python
import swapper

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # Originally was
        # migrations.swappable_dependency(settings.REUSABLEAPP_THING_MODEL)
        # which resolves reuseable.0001_initial, which contains migrations
        # for the model specified in REUSABLEAPP_THING_MODEL
        # ----------------------------------------------------------------
        # Resolves to reuseable.0001_initial
        swapper.dependency('reusableapp', 'Thing'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewThing',
            fields=[
                ...
            ],
            # Note that there is no 'swappable' key to the model options for
            # the swapped-in model, because this model is *not* marked
            # as swappable
        ),
    ]
```

finally you'll need to tell Django to swap out `Thing` for `NewThing`:

`<project>/settings.py`:

```python
...

REUSEABLE_THING_MODEL = 'myapp.NewThing'

...
```

In that case, **when are run for the first time** Django will run through the migrations for `reuseable`. It will see that you have set `REUSEABLE_THING_MODEL` in your settings so it won't create that model in the database. Then Django will run through the migrations for `myapp` *after* the migrations for `reuseable` because you have set the dependency in `myapp/migrations/0001_initial.py`, and once it does it will create the table for `Thing` in the database. In terms of migrations, that's all it does.

The documentation isn't 100% accurate and should be corrected.
