### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by skrivanos** [openwisp/django-swappable-models#18]
Hi,

This API seems like the perfect fit for a new project of mine, but I'm wondering if it has been abandoned? No official 2.x support yet nor any commits in the main branch for 2 years. Should I assume that if we decide to use it we'll have to maintain it ourselves?

Thanks!

**Comment by jpic** [comment]
Maybe ask Django if they want contribution

**Comment by sheppard** [comment]
Hi, I finally released the official Django 2 support in swapper 1.1.1.  I admit that there has been little activity here, primarily for two reasons:

1. The `swapper` API is relatively stable and has not needed any changes for over 2 years.  Most of the heavy lifting is done by Django.
2. The issues that do exist are related to the underlying Django implementation, so fixing them would require updates to Django.

In particular, there are a number of problems related to migrations (#10, #12, #14) that will be hard to address without a deep understanding of Django's internal model code.  While these issues may not be an dealbreaker for most common uses of `swapper`, they have become so for me.

I would say that `swapper` makes the most sense when there is at most one (or maybe two) models in your reusable application that you want to allow users to swap.  Once you have more than that, it gets to be a real mess for your users to keep track of migrations and remember where fields are defined.  For that reason, I am moving my own projects away from this approach (e.g. see wq/vera#7).

It is clear that `swapper` is useful for many people, and I will continue to accept PRs and make releases as I am able.  That said, I would be open to transferring ownership to someone with a more compelling ongoing interest in the project.

**Comment by nemesisdesign** [comment]
In case it helps, in @openwisp we're using this a lot, it is helping us to provide a standardized way to extend our modules and reduce boilerplate code.

Without swappable, if we wanted to allow creating customized versions of one of our modules, we had to separate the generic views from the concrete views, abstract admin from concrete admin, base tests from actual tests. With swappable we can avoid doing all that which makes our life easier and so far we have not encountered blockers.

So if you need help with maintenance, let us know.

**Comment by sheppard** [comment]
@nemesisdesign, would you be interested in taking this project over (and presumably moving it to @openwisp)?  I can grant access to the PyPI package as well.  If you would like, I can make one last release incorporating #23 and potentially #21 (cc @pandafy).

**Comment by nemesisdesign** [comment]
@sheppard, yes, I am available for this, since we use this module extensively now, we'll take care of its maintenance.

**Comment by nemesisdesign** [comment]
Thanks @sheppard for you collaboration :+1: :+1:.
This project is now maintained by OpenWISP and @sheppard will help us during the transition.
No big changes are planned, only maintenance and bugfixes.
