### ISSUE TITLE
[change] Allow passing a specific migration number

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-swappable-models#43]
In some cases, apps we depend on have data migrations we must depend on which are not included in the initial migration but may be included in the successive migrations.

Depending on latest doesn't fix that and may introduce more harm than good.
In these cases we simply have to depend on the specific migration and recommend anyone wanting to swap that particular app to create a migration with the same name in their swapped models.

I think we should change `dependency` as follows:

https://github.com/openwisp/django-swappable-models/blob/6698b200fc857a1c147406aa2d0ad8feab017408/swapper/__init__.py#L47-L55

- drop latest argument which may do more harm than good
- add a `version` attribute which defaults to `None` and if present is returned similary to how we return `__latest__` now

We should then update the docs about latest and replace those with this concept.

@codesankalp what do you think?

PS: see also https://github.com/openwisp/openwisp-users/pull/300.

**Comment by nemesisdesign** [comment]
I think this was a false alarm, but let me dig deeper and do more testing before closing.
I think latest can work fine if everything is set up correctly.

**Comment by codesankalp** [comment]
> @codesankalp what do you think?

Yes I also faced this in openwisp-radius. I will add a patch for this.
